@startuml Architecture
cloud {
    [Internet] #Yellow
}
Internet --> Game
Internet --> Lobby
node "Fireport Server" {
    Lobby -- [REST Server]
    Game -- [REST Server]
    
    package "Communication Layer" {
        [REST Server] --> [Routing]
        [PubSub] -up-> Internet
        [Routing] -left-> [PubSub]
    }

    package "Services" {
        [Routing] --> [LobbyService]
        [Routing] --> [GameService]
        [Routing] --> Internet
    }

    package "Game Logic" {
        [GameService] -- [Core logic]
    }
}
@enduml