---
- hosts: server
  user: ubuntu
  become: yes
  tasks:
    - name: Load the fireport container tarball
      raw: docker load -i fireport-container.tar
    - name: Prune unused images
      raw: docker image prune -f
    - name: Restart the docker container
      docker_container:
        name: fireport
        image: bitdecaygames/fireport
        state: started
        recreate: yes
        ports:
          - "8080:8080"





