---
- hosts: all
  gather_facts: False
  tasks:
    - name: install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: yes

- name: Install Nginx
  hosts: server
  user: ubuntu
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: restart nginx
      service:
        name=nginx
        state=restarted

